package com.cloderia.helion.client.shared.model;

import java.util.Date;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * ${entity.name} generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = ${entity.name}.ALL_ENTITIES_QUERY, query = "SELECT e FROM ${entity.name} e ORDER BY e.id")
})
@Table(name="${entity.name?lower_case}"
    ,catalog="helion"
)
public class ${entity.name} extends BaseEntity implements java.io.Serializable {

	public static final String ALL_ENTITIES_QUERY = "all${entity.name}s";
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    private Long id;
<#list entity.fields as field>

<#if field.relationshipField == "N">
    <#if field.dataType == "alphanumeric">
    private String ${field.javaName};
    </#if>
    <#if field.dataType == "name">
    private String ${field.javaName};
    </#if>
    <#if field.dataType == "text">
    private String ${field.javaName};
    </#if>
    <#if field.dataType == "email">
    private String ${field.javaName};
    </#if>
    <#if field.dataType == "date">
    private Date ${field.javaName};
    </#if>
    <#if field.dataType == "number">
    private BigDecimal ${field.javaName};
    </#if>
    <#if field.dataType == "text-lg">
    private String ${field.javaName};
    </#if>
</#if>
<#if field.relationshipField == "Y">
		<#list module.entities as modEntity>
            <#if field.dataType == modEntity.postName>
    private ${modEntity.name} ${field.javaName};
            </#if>
        </#list>
</#if>
</#list>

    public ${entity.name}() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
<#list entity.fields as field>

<#if field.relationshipField == "N">
    <#if field.dataType == "alphanumeric">
    @Column(name="${field.name}", nullable=false, length=35)
    public String get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(String ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "name">
    @Column(name="${field.name}", nullable=false, length=35)
    public String get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(String ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "text">
    @Column(name="${field.name}", nullable=false, length=35)
    public String get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(String ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "email">
    @Column(name="${field.name}", nullable=false, length=35)
    public String get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(String ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "date">
    @Column(name="${field.name}", nullable=false, length=35)
    public Date get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(Date ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "number">
    @Column(name="${field.name}", nullable=false, length=35)
    public BigDecimal get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(BigDecimal ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
    <#if field.dataType == "text-lg">
    @Column(name="${field.name}", nullable=false, length=35)
    public String get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(String ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
    </#if>
</#if>
<#if field.relationshipField == "Y">
		<#list module.entities as modEntity>
            <#if field.dataType == modEntity.postName>
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="${field.name}", nullable=false)
    public ${modEntity.name} get${field.javaName?cap_first}() {
        return this.${field.javaName};
    }
    
    public void set${field.javaName?cap_first}(${modEntity.name} ${field.javaName}) {
        this.${field.javaName} = ${field.javaName};
    }
            </#if>
        </#list>
</#if>
</#list>

}


